# Generated by Django 6.0.1 on 2026-03-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantadome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoexperiment',
            name='user',
            field=models.CharField(default='guest', max_length=50),
        ),
    ]
